### PR TITLE
fix: Remove horizontal scroll from match vouchers tab

### LINKED ISSUE #48: Make "Match Voucher" clear and responsive
### Problem

We have too much data in the horizontal direction to fit into the "Match Voucher" tab as a table. On my big screen, I can only see five of seven columns, which makes it look a bit convoluted and requires horizontal scrolling, which is unusual.

### Proposed solution

- Render each **Bank Transaction** as a card.
- Cards use the full width of the "Match Voucher" tab (minus some padding) and are stacked vertically.
- Have a "Reconcile" button on every card.
- Display the match reasons by highlighting the data points in bold and/or color?

### PR DESCRIPTION
**Pull request by marination**
Solves https://github.com/alyf-de/banking/issues/48

- Adjusted horizontal space between transactions list and actions area
- Reduced scrollbar idth of transactions area
- Adjusted column widths of datatable
- Document Type field moved to end of datatable. Its not an important column and often has repetitive information

## Before:
- The important columns are not all visible
- LHS is has some whitespace since its taking up way more space than it needs
- Horizontal scroll
Screenshot 2023-11-03 at 12 24 28 PM

## After:
- Match reasons are highlighted in bold. One less action for users
- No horizontal scroll
- Reference, Party and Voucher are left aligned
Screenshot 2023-11-06 at 4 03 59 PM

### CODE REVIEW

File: banking/public/js/bank_reconciliation_beta/actions_panel/match_tab.js [hunk 1]
```diff
@@ -473,11 +468,16 @@ erpnext.accounts.bank_reconciliation.MatchTab = class MatchTab {
...
 				format: (value, row, column, data) => {
-					return frappe.format(value, {fieldtype: "Link", options: data[1]});
+					return frappe.format(value, {fieldtype: "Link", options: data[6]});
 				},
 			},
+			{
+				name: __("Document Type"),
+				editable: false,
+				width: 50,
+			},
```
Comment (barredterra) [inline banking/public/js/bank_reconciliation_beta/actions_panel/match_tab.js]: Could we even set this to hidden and only use it for formatting the link in Document Name? Usually the doctype should be obvious from the naming series.

**Comment by barredterra** [comment]
I pushed the cleanup a bit further:

- Format remaining amount only for display, not storage (#79)
- Format docname as link, remove doctype column
- Format party as link
- Now we have more space and I didn't want to fine tune the widths again, so I changed the layout to "fluid"
- Removed the index column for even more space

Bildschirmfoto 2023-11-05 um 20 14 55

Remaining issues (can be solved in a separate PR):

- [x] Reference, Party and Voucher should be left aligned
- [x] Format individual cells as bold or with background to show which values matched, remove "Reason" column

Feel free to merge

**Comment by marination** [comment]
Updated description
